# Generated by Django 3.2.12 on 2022-03-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_auto_20220317_2155"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProblemMedia",
        ),
    ]
