# Generated by Django 3.2.12 on 2022-03-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_delete_problemmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProblemMedia')),
            ],
        ),
    ]
