# Generated by Django 3.2.12 on 2022-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_problemmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="media_ids",
            field=models.TextField(blank=True, null=True),
        ),
    ]
